openapi: 3.0.0
info:
  title: Products API
  description: API to manage products.
  version: 1.0.0
servers:
  - url: https://gkceqdno3g.execute-api.eu-north-1.amazonaws.com/prod
paths:
  /products:
    get:
      summary: List all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 453e0b55-20af-46cf-acc7-708c11e09698
                    title:
                      type: string
                      example: Product 1
                    description:
                      type: string
                      example: description of product 1
                    price:
                      type: number
                      format: float
                      example: 100
                    count:
                      type: integer
                      example: 10
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Product 1
                description:
                  type: string
                  example: description of product 1
                price:
                  type: number
                  format: float
                  example: 100
                count:
                  type: integer
                  example: 10
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 453e0b55-20af-46cf-acc7-708c11e09698
                  title:
                    type: string
                    example: Product 1
                  description:
                    type: string
                    example: description of product 1
                  price:
                    type: number
                    format: float
                    example: 100
                  count:
                    type: integer
                    example: 10
        '400':
          description: Invalid input
  /products/{product_id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 453e0b55-20af-46cf-acc7-708c11e09698
                  title:
                    type: string
                    example: Product 1
                  description:
                    type: string
                    example: description of product 1
                  price:
                    type: number
                    format: float
                    example: 100
                  count:
                    type: integer
                    example: 10
        '404':
          description: Product not found
