openapi: 3.0.0
info:
  title: Products API
  description: API to manage products.
  version: 1.0.0
servers:
  - url: https://gkceqdno3g.execute-api.eu-north-1.amazonaws.com/prod
paths:
  /products:
    get:
      summary: List all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: Product 1
                    color:
                      type: string
                      example: red
                    price:
                      type: number
                      format: float
                      example: 100
  /products/{product_id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  title:
                    type: string
                    example: Product 1
                  color:
                    type: string
                    example: red
                  price:
                    type: number
                    format: float
                    example: 100
        '404':
          description: Product not found
